### ISSUE TITLE
BUG: frontend docker container doesn't recompile sources

### ISSUE THREAD

**Issue by zlapik** [Alschn/django-react-docker-heroku-template#5]
Based on [stackoverflow question](https://stackoverflow.com/a/72661752) and my own experience I figured out that I've changed ***docker-compose.yml*** frontend service to:
```docker
  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - node-modules:/app/frontend/node_modules
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      # - CHOKIDAR_USEPOLLING=true # not working anymore
    restart: always
```

**Comment by Alschn** [comment]
Thank you for submitting this issue. You are right. I remember having this problem on one of my recent projects after bumping React to version 18. I added `WATCHPACK_POLLING=true` in that project but I must have forgotten to update this repository.
